export enum OrderStatus {
    NEW = 'NEW',
    PENDING_APPROVAL = 'PENDING APPROVAL',
    PENDING_ASSIGNMENT = 'PENDING ASSIGNMENT',
    PROCESSING = 'PROCESSING',
    DELIVERING = 'DELIVERING',
    COMPLETED = 'COMPLETED',
    REFUNDED = 'REFUNDED',
    CANCELED = 'CANCELED'
}

export enum PaymentOrderStatus {
    INITIATED = 'INITIATED',
    NEW = 'NEW',
    PENDING = 'PENDING',
    COMPLETED = 'COMPLETED'
} 